LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := Ango
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := Ango_4.2.apk
LOCAL_PACKAGE_NAME := com.maxpatchs.ango
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)
