LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := LuxDark_3.6
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := LuxDark_3.6apk
LOCAL_PACKAGE_NAME := com.benx9.luxdark
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)
