LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := Drift Music
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := Drift Music [1.2.3].apk
LOCAL_PACKAGE_NAME := Drift Music
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_OVERRIDES_PACKAGES := Music MusicPlayer SnapdragonMusic crDroidMusic Phonograph Eleven VanillaMusic
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)
