LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := Edge Action [1.2.5]
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := Edge Action [1.2.5].apk
LOCAL_PACKAGE_NAME := com.edgescreen.edgeaction
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)
